# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TealiumUsabillaExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TealiumUsabillaExample
  pod 'TealiumUsabilla', :path=> '../'
  pod 'tealium-swift/Lifecycle', '~> 2.1'

end
